#ifndef PNGYU_DIFINES_H
#define PNGYU_DIFINES_H

namespace pngyu
{

enum CompressOptionMode
{
  COMPRESS_OPTION_UNKNOWN = -1,
  COMPRESS_OPTION_DEFAULT = 0,
  COMPRESS_OPTION_CUSTOM
};

enum OutputOptionMode
{
  OUTPUT_OPTION_UNKNOWN = -1,
  OUTPUT_OPTION_OVERWITE_ORIGIANL = 0,
  OUTPUT_OPTION_CUSTOM
};

enum OuputDirectoryMode
{
  OUTPUT_DIR_UNKNOWN = -1,
  OUTPUT_DIR_SAME = 0,
  OUTPUT_DIR_OTHER
};

enum OutputFinenameMode
{
  OUTPUT_FILE_UNKNOWN = -1,
  OUTPUT_FILE_SAME_AS_ORIGINAL = 0,
  OUTPUT_FILE_CUSTOM
};


}

#endif // PNGYU_DIFINES_H
